name: On Push

on: push

jobs:
  jest:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run test
        run: npx jest
